services:
  devops:
    build: .
    image: devops:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - OBNet

networks:
  OBNet:
    external: true

#> docker compose up --build -d