name: CD
on:
  push:
    branches: ['master']

env:
  REPOSITORY: ${{ github.repository }} # <user>/<repo>
  GHCR_URL: ghcr.io # GitHub Container Registry

jobs:
  cd:
    name: Deploy database into AWS Lightsail
    runs-on: ubuntu-22.04

    steps:
      - name: 🚀 Deploy on AWS Lightsail
        uses: appleboy/ssh-action@v1.2.1
        with:
            host: ${{ secrets.AWS_LIGHTSAIL_IP_MAIN }}
            username: ${{ secrets.AWS_LIGHTSAIL_USERNAME }}
            key: ${{ secrets.AWS_LIGHTSAIL_SSH }}
            script: |
              sudo docker rm -f postgres-server || true
              sudo docker network create OBNet || true
              sudo docker run -d \
                --name ${{ env.ARTIFACT }} \
                --restart always \
                --network OBNet \
                -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
                -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
                -e POSTGRES_DB=ObDb \
                postgres:15.10